//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Data.DBAccessor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataClassesDataContext : DbContext
    {
        public DataClassesDataContext()
            : base("name=DataClassesDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Emp_Skill> TBL_Emp_Skill { get; set; }
        public virtual DbSet<TBL_Flight_Schedule> TBL_Flight_Schedule { get; set; }
        public virtual DbSet<TBL_ProductList> TBL_ProductList { get; set; }
    
        public virtual ObjectResult<Cefiticate_Result> Cefiticate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cefiticate_Result>("Cefiticate");
        }
    
        public virtual int UpdateAirlinescode()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAirlinescode");
        }
    
        public virtual int UpdateAirlinescodeC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAirlinescodeC");
        }
    }
}
