//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ProductList
    {
        public int Id { get; set; }
        public long ID_Code { get; set; }
        public string sProductCode { get; set; }
        public string sProductName { get; set; }
        public string sShortName { get; set; }
        public string FK_sAirline { get; set; }
        public string sAC { get; set; }
        public string sLoadProperty { get; set; }
        public string sCarry { get; set; }
        public Nullable<byte> iArrDep { get; set; }
        public string sDomInt { get; set; }
        public string sTimeBase { get; set; }
        public Nullable<short> iStartTime { get; set; }
        public Nullable<byte> iDuringTime { get; set; }
        public Nullable<byte> iManQuota { get; set; }
        public Nullable<decimal> eMinutesOnePerson { get; set; }
        public Nullable<long> iUnitPrice { get; set; }
    }
}
