//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Emp_Skill
    {
        public int Id { get; set; }
        public long ID_Code { get; set; }
        public string FK_sEmpID { get; set; }
        public Nullable<bool> bBXE { get; set; }
        public Nullable<bool> bBXM { get; set; }
        public Nullable<bool> bBXL { get; set; }
        public Nullable<bool> bCCH { get; set; }
        public Nullable<bool> bCDU { get; set; }
        public Nullable<bool> bWGD { get; set; }
        public Nullable<bool> bBTA { get; set; }
        public Nullable<bool> bDKE { get; set; }
        public Nullable<bool> bXNG { get; set; }
        public Nullable<bool> bXNM { get; set; }
        public Nullable<bool> bXNL { get; set; }
    }
}
