//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Flight_Schedule
    {
        public int ID { get; set; }
        public string ARR_ID { get; set; }
        public string DEP_ID { get; set; }
        public Nullable<int> AIRLINE_COMPANY_ID { get; set; }
        public string AIRLINE_COMPANY_CODE { get; set; }
        public string ARR_NO { get; set; }
        public string DEP_NO { get; set; }
        public string FLT_NO { get; set; }
        public string AIRCRAFT { get; set; }
        public string REGISTER { get; set; }
        public string ROUTE { get; set; }
        public string ETA { get; set; }
        public string STA { get; set; }
        public string ATA { get; set; }
        public string ETD { get; set; }
        public string STD { get; set; }
        public string ATD { get; set; }
        public Nullable<System.DateTime> FLIGHT_DAY { get; set; }
        public string PARKING_CODE { get; set; }
        public string ARR_REMARK { get; set; }
        public string DEP_REMARK { get; set; }
        public string ARR_QTQN { get; set; }
        public string DEP_QTQN { get; set; }
        public string PC1 { get; set; }
        public string PC2 { get; set; }
        public string Active { get; set; }
        public string Belt { get; set; }
        public Nullable<System.DateTime> tmpLT_STA { get; set; }
        public Nullable<System.DateTime> tmpLT_STD { get; set; }
        public Nullable<int> CHANGED_STATUS { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
